language: ruby
sudo: enabled
dist: trusty
before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y && sudo apt-get update
  - sudo apt-get install automake bison flex g++ git libboost1.55-all-dev libevent-dev libssl-dev libtool make pkg-config -y
  - sudo apt-get install libthrift-dev
  - gem install bundler --no-document

rvm:
  - 1.9.3
  - 2.1.8
  - 2.2.1
  - 2.3.0
script:
  # Please add to Rakefile instead of this section.
  - bundle exec rake
  - bundle exec rubocop
